### PR TITLE
Add support for getting query models from `sqlalchemy.sql.Select` instance

### PR DESCRIPTION
**Pull request by ArkhipovNikita**
I added support for using `sqlalchemy.sql.Select` instance to be able to use `sqlalchemy.ext.asyncio.AsyncSession` from SQLAlchemy 1.4 that doesn't have query object and is used with core-level functions.

### CODE REVIEW

**Comment by bodik** [comment]
hi, thank you for your contribution.

I'm trying to figure out how to fix the failing CI (failing coverage) but I cannot properly replicate working filters for asyncio with or without this PR. the example i'm trying to test fails. Thanks for any help.


### test_asyncio.py
```
import asyncio

from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import select

from sqlalchemy_filters import apply_filters


Base = declarative_base()

class t1(Base):
    __tablename__ = 't1'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)


async def async_main():
    engine = create_async_engine(
        "postgresql+asyncpg://user:password@localhost:5432/test_sqlalchemy_filters", echo=True,
    )

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

        await conn.execute(
            t1.__table__.insert(), [{"name": "some name 1"}, {"name": "some name 2"}]
        )

    async with engine.connect() as conn:
        result = await conn.execute(select(t1.__table__).where(t1.__table__.c.name == "some name 1"))
        print(result.fetchall())

    async with engine.connect() as conn:
        result = await conn.execute(apply_filters(select(t1.__table__), {'field': 'name', 'op': '==', 'value': 'some name 2'}))
        print(result.fetchall())

    await engine.dispose()

asyncio.run(async_main())
```

### test run
```
Traceback (most recent call last):
  File "test_asyncio.py", line 42, in <module>
    asyncio.run(async_main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test_asyncio.py", line 37, in async_main
    result = await conn.execute(apply_filters(select(t1.__table__), {'field': 'name', 'op': '==', 'value': 'some name 2'}))
  File "/opt/sqlalchemy-filters/sqlalchemy_filters/filters.py", line 235, in apply_filters
    default_model = get_default_model(query)
  File "/opt/sqlalchemy-filters/sqlalchemy_filters/models.py", line 201, in get_default_model
    query_models = get_query_models(query).values()
  File "/opt/sqlalchemy-filters/sqlalchemy_filters/models.py", line 105, in get_query_models
    models = [col_desc['entity'] for col_desc in query.column_descriptions]
  File "/opt/sqlalchemy-filters/venv/lib/python3.7/site-packages/SQLAlchemy-1.4.26-py3.7-linux-x86_64.egg/sqlalchemy/sql/selectable.py", line 5255, in column_descriptions
    return meth(self)
  File "/opt/sqlalchemy-filters/venv/lib/python3.7/site-packages/SQLAlchemy-1.4.26-py3.7-linux-x86_64.egg/sqlalchemy/sql/selectable.py", line 4308, in get_column_descriptions
    cls._plugin_not_implemented()
  File "/opt/sqlalchemy-filters/venv/lib/python3.7/site-packages/SQLAlchemy-1.4.26-py3.7-linux-x86_64.egg/sqlalchemy/sql/selectable.py", line 4302, in _plugin_not_implemented
    "The default SELECT construct without plugins does not "
NotImplementedError: The default SELECT construct without plugins does not implement this method.
```

**Comment by ArkhipovNikita** [comment]
> test_sqlalchemy_filters

Hi, thanks for your interest, I'm glad of it. 
In the second option with selecting with asynаcio you shouldn't pass `t1.__table__` , just `t1` and everything will work. 

```
async with engine.connect() as conn:
    result = await conn.execute(apply_filters(select(t1), {'field': 'name', 'op': '==', 'value': 'some name 2'}))
    print(result.fetchall())
```

**Comment by ArkhipovNikita** [comment]
@bodik, as far as I understand I should write tests to get models from `sqlalchemy.sql.Select` instance,  shouldn't I?

**Comment by bodik** [comment]
> @bodik, as far as I understand I should write tests to get models from `sqlalchemy.sql.Select` instance, shouldn't I?

Yeah, that would be wonderful. In this particular case the code inferring model names is trying to handle an always changing sqlalchemy internals as best it can, but also we should keep coverage at highest possible level so I'm trying to come up with some refactored code which will be a bit simpler (not sure if there such).

But any idea or suggestion is welcome.

**Comment by bodik** [comment]
@ArkhipovNikita i've shuffled code a bit in https://github.com/bodik/sqlalchemy-filters/pull/3, would that work for you ?

**Comment by bodik** [comment]
i guess we might close this in favor of https://github.com/bodik/sqlalchemy-filters/pull/3 now merged to default `master-forked` branch

**Pull request closed without merging**
